[package]
name = "env_logger_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# For logging and command line operations
log = "0.4"
env_logger = "0.9"
structopt = "0.3"
chrono= "*"